export const designTokens = {
  colors: [
    { name: 'Blue Primary', value: 'var(--color-blue-primary)' },
    { name: 'Blue Light', value: 'var(--color-blue-light)' },
    { name: 'Blue Dark', value: 'var(--color-blue-dark)' },
    { name: 'Teal', value: 'var(--color-teal)' },
    { name: 'Purple', value: 'var(--color-purple)' },
    { name: 'Black', value: 'var(--color-black)' },
    { name: 'Charcoal', value: 'var(--color-charcoal)' },
    { name: 'Dark Gray', value: 'var(--color-dark-gray)' },
    { name: 'White', value: 'var(--color-white)' },
    { name: 'Gray 100', value: 'var(--color-gray-100)' },
    { name: 'Gray 200', value: 'var(--color-gray-200)' },
    { name: 'Gray 300', value: 'var(--color-gray-300)' },
    { name: 'Gray 400', value: 'var(--color-gray-400)' },
    { name: 'Gray 500', value: 'var(--color-gray-500)' },
    { name: 'Gray 600', value: 'var(--color-gray-600)' },
    { name: 'Gray 700', value: 'var(--color-gray-700)' },
    { name: 'Success', value: 'var(--color-success)' },
    { name: 'Warning', value: 'var(--color-warning)' },
    { name: 'Error', value: 'var(--color-error)' },
    { name: 'Info', value: 'var(--color-info)' },
  ],
  fontFamily: [
    { name: 'Primary', value: 'var(--font-family-primary)' },
    { name: 'Monospace', value: 'var(--font-family-monospace)' },
  ],
  fontSize: [
    { name: 'XS', value: 'var(--font-size-xs)' },
    { name: 'SM', value: 'var(--font-size-sm)' },
    { name: 'Base', value: 'var(--font-size-base)' },
    { name: 'MD', value: 'var(--font-size-md)' },
    { name: 'LG', value: 'var(--font-size-lg)' },
    { name: 'XL', value: 'var(--font-size-xl)' },
    { name: '2XL', value: 'var(--font-size-2xl)' },
    { name: '3XL', value: 'var(--font-size-3xl)' },
    { name: '4XL', value: 'var(--font-size-4xl)' },
  ],
  spacing: [
    { name: '0', value: 'var(--space-0)' },
    { name: '1', value: 'var(--space-1)' },
    { name: '2', value: 'var(--space-2)' },
    { name: '3', value: 'var(--space-3)' },
    { name: '4', value: 'var(--space-4)' },
    { name: '5', value: 'var(--space-5)' },
    { name: '6', value: 'var(--space-6)' },
    { name: '8', value: 'var(--space-8)' },
    { name: '10', value: 'var(--space-10)' },
    { name: '12', value: 'var(--space-12)' },
    { name: '16', value: 'var(--space-16)' },
    { name: '20', value: 'var(--space-20)' },
    { name: '24', value: 'var(--space-24)' },
    { name: '32', value: 'var(--space-32)' },
  ],
  radii: [
    { name: 'None', value: 'var(--radius-none)' },
    { name: 'SM', value: 'var(--radius-sm)' },
    { name: 'MD', value: 'var(--radius-md)' },
    { name: 'LG', value: 'var(--radius-lg)' },
    { name: 'XL', value: 'var(--radius-xl)' },
    { name: '2XL', value: 'var(--radius-2xl)' },
    { name: 'Full', value: 'var(--radius-full)' },
  ],
  shadows: [
    { name: 'None', value: 'var(--shadow-none)' },
    { name: 'SM', value: 'var(--shadow-sm)' },
    { name: 'MD', value: 'var(--shadow-md)' },
    { name: 'LG', value: 'var(--shadow-lg)' },
    { name: 'XL', value: 'var(--shadow-xl)' },
    { name: 'Inner', value: 'var(--shadow-inner)' },
    { name: 'Card', value: 'var(--shadow-card)' },
  ],
  durations: [
    { name: 'Instant', value: 'var(--duration-instant)' },
    { name: 'Fast', value: 'var(--duration-fast)' },
    { name: 'Normal', value: 'var(--duration-normal)' },
    { name: 'Slow', value: 'var(--duration-slow)' },
  ],
  easings: [
    { name: 'Default', value: 'var(--ease-default)' },
    { name: 'In', value: 'var(--ease-in)' },
    { name: 'Out', value: 'var(--ease-out)' },
    { name: 'In Out', value: 'var(--ease-in-out)' },
  ],
}; 